[package]
name = "rustypod"
version = "0.0.0"
authors = ["John Ramsden <johnramsden@riseup.net>", "Joe Puthenkulam <joeputhenkulam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
